# Generated by Django 4.1.6 on 2023-02-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=30)),
                ('product_no', models.BigIntegerField()),
                ('product_des', models.CharField(max_length=60)),
                ('price', models.IntegerField(default=0)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'products_tb',
            },
        ),
    ]
