# Generated by Django 4.1.6 on 2023-02-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_products_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
