# Generated by Django 4.1.6 on 2023-02-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ang_eco_admin', '0002_alter_category_category_image'),
        ('seller', '0007_delete_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ang_eco_admin.category'),
        ),
    ]
