# Generated by Django 4.1.6 on 2023-02-18 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_alter_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='seller',
        ),
    ]
