# Generated by Django 4.1.6 on 2023-02-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_customer'),
        ('ang_eco_admin', '0002_alter_category_category_image'),
        ('seller', '0009_remove_products_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='common.seller'),
        ),
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ang_eco_admin.category'),
        ),
    ]
