# Generated by Django 4.1.6 on 2023-02-18 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ang_eco_admin', '0002_alter_category_category_image'),
        ('seller', '0011_remove_products_category_alter_products_product_des_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ang_eco_admin.category'),
        ),
    ]
