# Generated by Django 4.1.6 on 2023-02-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('user_name', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=60)),
                ('bank_name', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=10)),
                ('account_no', models.CharField(max_length=15)),
                ('seller_pic', models.ImageField(upload_to='seller/')),
            ],
            options={
                'db_table': 'seller_tb',
            },
        ),
    ]
