# Generated by Django 4.1.6 on 2023-02-12 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='seller',
            name='user_name',
            field=models.IntegerField(default=0),
        ),
    ]
