# Generated by Django 4.1.6 on 2023-02-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_seller_password_alter_seller_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_pic',
        ),
    ]
