# Generated by Django 4.1.6 on 2023-02-12 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_seller_seller_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='seller_pic',
            field=models.ImageField(default=11, upload_to='sellerpic/'),
            preserve_default=False,
        ),
    ]
