# Generated by Django 4.1.6 on 2023-02-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_seller_seller_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=40)),
                ('customer_pic', models.ImageField(upload_to='customerpic/')),
            ],
            options={
                'db_table': 'customer_tb',
            },
        ),
    ]
