# Generated by Django 4.1.6 on 2023-02-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30)),
                ('category_des', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='category_image/')),
            ],
            options={
                'db_table': 'category_tb',
            },
        ),
    ]
