# Generated by Django 4.1.6 on 2023-02-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ang_eco_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.FileField(upload_to='category_image/'),
        ),
    ]
